name: apklis_dart_flutter

packages:
  - packages/**

scripts:
  build:
    run: melos exec "dart pub run build_runner build --delete-conflicting-outputs"

  test:
    run: melos exec "dart test"

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.5.3
