site_name: Apklis Dart/Flutter Ecosystem
site_url: https://github.com/fluttercuba/apklis-dart-flutter
repo_url: https://github.com/fluttercuba/apklis-dart-flutter
edit_uri: https://github.com/fluttercuba/apklis-dart-flutter/edit/main/docs

theme:
  name: material
  language: en
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fluttercuba
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FlutterCuba
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/fluttercubachat
      name: Telegram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCfrx_w0XAJxY5FHoWP5T8tw
      name: Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:fluttercuba@gmail.com
      name: Email
