name: apklis_http_web_api
description: Implementación concreta del paquete apklis_web_api para interactuar con la API de Apklis utilizando el paquete http.
version: 0.0.0
homepage: https://github.com/fluttercuba/apklis-dart-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  apklis_web_api: ^0.0.1+2
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mocktail: ^0.1.4
  test: ^1.17.5
