name: apklis_direct_payment_checker
description: Paquete de Flutter para el chequeo de pagos de Apklis. Basado en el
  repositorio para Kotlin y Java https://github.com/Z17-CU/apklischeckpayment
version: 0.0.1
homepage: https://github.com/fluttercuba/apklis-dart-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.0.6

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercuba.apklis_direct_payment_checker
        pluginClass: ApklisDirectPaymentCheckerPlugin
