name: apklis_web_api
description: Interfaz para la posterior implementación de un paquete en Dart
  para interactuar con la API de Apklis.
version: 0.2.0+1
homepage: https://github.com/fluttercuba/apklis-dart-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mocktail: ^0.1.4
  test: ^1.17.5
