name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2

      - name: 'Install Flutter'
        uses: subosito/flutter-action@v1

      - name: 'Install Tools'
        run: flutter pub global activate melos

      - name: 'Bootstrap Workspace'
        run: flutter pub global run melos bootstrap

      - name: 'Test'
        run: flutter pub global run melos run test
