name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2

      - name: 'Install Dart'
        uses: dart-lang/setup-dart@v1

      - name: 'Run Tests'
        run: |
          dart pub global activate melos
          dart pub global run melos clean
          dart pub global run melos bootstrap
          dart pub global run melos run test
