name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Run Melos Bootstrap
        run: melos bs

      - name: Run Tests
        run: melos run test

      - name: Install tools for Coverage
        run: melos run cov:install

      - name: Merge and Clean Coverage files
        run: melos run cov:merge

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: coverage/lcov.info
